import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import { LoadingProvider } from "@/components/providers/loading-provider";
import { TRPCProvider } from "@/server/trpc/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Styliz System",
  description: "Generated by create kielo",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <TRPCProvider>
            <main className="relative">
              <LoadingProvider>
                {children}
              </LoadingProvider>
              <Toaster />
            </main>
          </TRPCProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
